config-version: 1 #don't modify!!!
license-key: "Wb5AQ0Q48DhMskSkwNxYmpwQKU2Wrrwh1h3mMjfG"

database:
  name: "database.db"
  history-default-limit: 20
  max-pool-size: 3

cache:
  max-players-in-cache: 1000
  expire-time: 10 #minutes

message-delay: 3 #seconds
max-word-length: 20

caps-options:
  max-caps: 50 #%
  min-letters: 2

import-export:
  backup-delay: 15 #minute
  default-extension: "txt"  #txt | json
  export-usage: "&cUsage: /moderation export <blacklist|whitelist> <json|txt>"
  type-error: "&cType must be: blacklist or whitelist"
  format-error: "cFormat must be: json or txt"
  exporting-message: "&eExporting %type% in %format% format..."
  exported-message: "&aExported &e%count% &awords to: &7%file%"
  export-error: "&cExport failed: %error%"
  #--------------------------------------------------------------------
  import-usage: "&cUsage: /moderation import <blacklist|whitelist> <json|txt> <filename> [merge|replace]"
  mode-error: "&cMode must be: merge or replace"
  file-not-found: "&File not found: ยง7imports/%file%"
  file-suggest: "&7Place the file in: %path%/imports/"
  importing-message: "&eImporting %type% from &7%file%. &e(%mode%)..."
  imported-message: "&aImport completed! Added: &e%count% &7| Skipped %skipped%"
  import-error: "&cImport failed: %error%"

messages:
  prefix: "&8&l[&6&lModeration&8&l] "
  noDelay: "&cYou must wait %time% seconds before sending a message again!"
  no-permission: "&cYou don't have permission to do that!"
  addWordToBlacklist: "&aSuccessfully added to the blacklist!"
  removeWordFromBlacklist: "&aSuccessfully removed from the blacklist!"
  addWordToWhitelist: "&aSuccessfully added to the whitelist!"
  removeWordFromWhitelist: "&aSuccessfully removed from the whitelist!"
  notBlacklisted: "&cThis word is not blacklisted!"
  blacklisted: "&cThis word is blacklisted!"
  notWhitelisted: "&cThis word is not whitelisted!"
  whitelisted: "&cThis word is whitelisted!"
  reload: "&aSuccessfully reloaded the config!"
  usage: "&cUsage: /moderation <add|remove|check> <blacklist|whitelist> <word>"
  usageHistory: "&cUsage: /moderation history <player> {limit}"
  noWord: "&cPlease specify a word!"
  only-integer: "&cPlease specify a valid integer!"
  onlyPlayers: "&cOnly players can use this command!"
  noCaps: "&cThis message has too many caps!"
  noEmptyWords: "&cYou can't add empty words!"
  wordTooLong: "&cThe word is too long! Max %max% characters!"
  onlyLettersNumbers: "&cThe word can only contain letters and numbers!"
  help:
    - "&6========== MODERATION HELP =========="
    - ""
    - "&e&lBasic Commands:"
    - "&a/moderation add <blacklist|whitelist> <word>  &7- Add a word"
    - "&a/moderation remove <blacklist|whitelist> <word>  &7- Remove a word"
    - "&a/moderation check <blacklist|whitelist> <word>  &7- Check a word"
    - "&a/moderation reload  &7- Reload the config"
    - "&a/moderation history <player> {limit}  &7- Check player history"
    - ""
    - "&e&lImport/Export:"
    - "&a/moderation export <blacklist|whitelist> <json|txt>  &7- Export list"
    - "&a/moderation import <blacklist|whitelist> <json|txt> <file> [merge|replace]  &7- Import list"
    - ""
    - "&7Example: &f/moderation export blacklist json"
    - "&7Example: &f/moderation import blacklist txt mylist.txt merge"
    - ""
    - "&6====================================="
  player-history:
    header: "&6========== %player% HISTORY =========="
    body:
      - ""
      - "&aDate: &7%date%"
      - "&aMessage: &7%message%"
      - "&aAction: &7%action%"
      - ""
    footer: "&6====================================="
  staff-segnalation: "&c%player% has sent a message with %word%"
  staff-sign-segnalation: "&c%player% has placed a sign with '%word%' in %location%"