database:
  name: "database.db"

check-interval: 30 #seconds
message-delay: 3 #seconds

caps-options:
  max-caps: 50 #%
  min-letters: 3

messages:
  prefix: "&8[&6Moderation&8] "
  noDelay: "&cYou must wait %time% seconds before sending a message again!"
  no-permission: "&cYou don't have permission to do that!"
  addWord: "&aSuccessfully added to the blacklist!"
  removeWord: "&aSuccessfully removed from the blacklist!"
  notBlacklisted: "&cThis word is not blacklisted!"
  blacklisted: "&cThis word is blacklisted!"
  reload: "&aSuccessfully reloaded the config!"
  usage: "&cUsage: /moderation <add|remove|check> <word>"
  noWord: "&cPlease specify a word!"
  onlyPlayers: "&cOnly players can use this command!"
  noCaps: "&cThis message has too many caps!"
  help:
    - "&g========== MODERATION HELP =========="
    - ""
    - "&a/moderation add <word>  &7- Add a word to the blacklist"
    - "&a/moderation remove <word>  &7- Remove a word from the blacklist"
    - "&a/moderation check <word>  &7- Check if a word is blacklisted"
    - "&a/moderation reload  &7- Reload the config"
    - ""
    - "&g====================================="
